version: '3'
services:
  # --- 1. 数据库配置 ---
  db:
    image: mysql:5.7
    container_name: mysql-container
    # 【重点修改这里】 加上了字符集设置
    command: --sql-mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tlias
    volumes:
      - ./mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
  # --- 2. 后端配置 ---
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "8080:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 300M
    # 【修改点 C】 这里的 command 非常关键！
    # 1. url=jdbc:mysql://db:3306...  (把 localhost 改成 db)
    # 2. username=root
    # 3. password=1234 (对应上面的密码)
    command: ["java", "-Xms256m", "-Xmx256m", "-jar", "/app.jar", "--spring.datasource.url=jdbc:mysql://db:3306/tlias?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai", "--spring.datasource.username=root", "--spring.datasource.password=1234"]

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend